name: mypipeline
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: |
          echo "Build running"
          sleep 5
      - name: second step or task
        run: |
          echo "Build completed"
          sleep 5
  test:
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - name: Run a one-line script
        run: |
          echo "Test running"
          sleep 5
      - name: second step or task
        run: |
          echo "Test completed"
          sleep 5
