name: mypipeline
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: |
          echo "Build running"
          sleep 30
      - name: second step or task
        run: |
          echo "Build completed"
          sleep 30
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: |
          echo "Test running"
          sleep 30
      - name: second step or task
        run: |
          echo "Test completed"
          sleep 30
