name: mypipeline
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: second step or task
        run: |
          echo "hello from step 21"
          sleep 10
      - name: create a file and list it
        run: |
          touch gagan.txt
          ls -l
          sleep 10
