name: Variable
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  home: "home1"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo ${{ secrets.password }}
          echo ${{ vars.username }}
      - name: Create a file
        run: echo $home
